"""Emit an apply_patch for a measured, still-experimental ones-lockout profile.

Input records come from locking_envelope, not an ideal regular pentagon.
The geometry acceptance test must check interpolation before adoption.
"""

import argparse
import json
from pathlib import Path


def records(path):
    return [json.loads(line) for line in Path(path).read_text().splitlines()
            if line.startswith('{')]


def compact(points, error=.01):
    """Keep both contact curves within error at every measured input knot."""
    if len(points) <= 2:
        return points
    first, last = points[0], points[-1]
    errors = []
    for point in points[1:-1]:
        fraction = (point[0]-first[0])/(last[0]-first[0])
        errors.append(max(abs(point[j]-first[j]-fraction*(last[j]-first[j]))
                          for j in (1, 2)))
    worst = max(errors)
    if worst <= error:
        return [first, last]
    split = errors.index(worst)+1
    return compact(points[:split+1], error)[:-1]+compact(points[split:], error)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('native')
    parser.add_argument('faceted')
    parser.add_argument('bands')
    parser.add_argument('--native-extra', action='append', default=[])
    parser.add_argument('--faceted-extra', action='append', default=[])
    parser.add_argument('--compact', action='store_true')
    args = parser.parse_args()
    native = {row['shaft']: row for row in records(args.native)}
    faceted = {row['shaft']: row for row in records(args.faceted)}
    for path in args.native_extra:
        native.update((row['shaft'], row) for row in records(path))
    for path in args.faceted_extra:
        faceted.update((row['shaft'], row) for row in records(path))
    bands = records(args.bands)
    assert len(bands) == 5 and all(row['bounds'] for row in bands)
    assert native.keys() == faceted.keys()
    lines = ['"""Experimental measured complete-bell/ones contact envelopes.',
             '', 'Generated by tools/compile_locking_profile.py; geometry validation',
             'is required before this can become a production restraint.',
             'Opening/closing knots retain the free-side bracket of BOTH kernels.',
             'No contact volume is discarded.', '"""', '', 'SECTORS = (']
    for i, band in enumerate(bands):
        # The .002-degree inset stays on the free side of the measured
        # closed-land bands. It is an explicit angular guard, not a volume
        # epsilon. Profiles below still need between-knot verification.
        start = band['bounds'][1]['last_free'] - .002
        following = bands[(i+1) % 5]
        end = following['bounds'][0]['last_free'] + .002 + (360 if i == 4 else 0)
        points = []
        for shaft in sorted(native):
            if not start < shaft < end:
                continue
            opening, closing = [], []
            for row in (native[shaft], faceted[shaft]):
                opens = [b['right'] for b in row['boundaries']
                         if not b['enters_contact'] and b['right'] < 90]
                closes = [b['left'] for b in row['boundaries']
                          if b['enters_contact'] and 90 < b['left'] < 180]
                if not opens:
                    # An inscribed mesh can miss the closed circular land
                    # near an indexed flat, including at crank zero. Never
                    # turn that absence into a physical release window: the
                    # native opening remains mandatory and governs instead.
                    assert row['kernel'] == 'faceted', shaft
                    assert all(volume <= 0 for angle, volume in row['samples']
                               if angle <= 90), shaft
                    opens = [0]
                assert closes, shaft
                opening.append(max(opens))
                closing.append(min(closes))
            points.append((shaft, max(opening), min(closing)))
        assert len(points) >= 3, i
        if args.compact:
            points = compact(points)
        lines.append(f'    ({start:.9f}, {end:.9f}, (')
        lines.extend(f'        ({shaft:.9f}, {opening:.9f}, {closing:.9f}),'
                     for shaft, opening, closing in points)
        lines.append('    )),')
    lines.append(')')
    if args.compact:
        lines.extend(['', '# Both curves compressed to <= .01 degree error at the measured knots.'])
    target = Path(__file__).resolve().parents[1] / 'locking_profiles.py'
    print('*** Begin Patch')
    if target.exists():
        print(f'*** Update File: {target}')
        print('@@')
        print('\n'.join('-'+line for line in target.read_text().splitlines()))
    else:
        print(f'*** Add File: {target}')
    print('\n'.join('+'+line for line in lines))
    print('*** End Patch')


if __name__ == '__main__':
    main()
