"""Compile the measured hook pocket into a small public motion profile."""

import json
import sys
from pathlib import Path
from simulation.tools.compile_detents import compact


def emit(path):
    rows = [json.loads(line) for line in Path(path).read_text().splitlines()
            if line.startswith('{')]
    points = compact([(row['lift'], row['spread'] + .05) for row in rows])
    lines = ['"""Measured drum-pocket profile with .05 mm radial seating allowance.',
             '', 'Generated by tools/compile_bell_spring.py; no live collision solving.',
             '"""', '', 'from machinome.math import piecewise', '', '', 'DEFLECTION = (']
    lines.extend(f'    ({x:g}, {y:.6f}),' for x, y in points)
    lines.extend([')', '', '', 'def positioning(source, target):',
                  '    return lambda subtract: piecewise(9 * subtract, DEFLECTION)'])
    target = Path(__file__).resolve().parents[1] / 'bell_spring_motion.py'
    print('*** Begin Patch')
    print(f'*** Add File: {target}')
    print('\n'.join('+' + line for line in lines))
    print('*** End Patch')


if __name__ == '__main__':
    emit(sys.argv[1])
