"""Emit a patch for a provisional counter-ones profile from measured records.

This is not geometry acceptance. Complete-print boundary and between-knot
checks are required before any law compiled from these sectors is adopted.
"""

import argparse
import hashlib
import json
from pathlib import Path


SHAFT_GUARD = .002


def compile_profile(rows, bands):
    for row in [*rows, *bands]:
        if row.get('station') != 1 or row.get('carry') != 0 or row.get('trial') is not True:
            raise ValueError('Profile requires the trial counter ones at carry 0')
        if row.get('kernel') not in ('native', 'faceted'):
            raise ValueError('Unknown comparison kernel')
    by_kernel = {kernel: {row['shaft']: row for row in rows if row['kernel'] == kernel}
                 for kernel in ('native', 'faceted')}
    if by_kernel['native'].keys() != by_kernel['faceted'].keys():
        raise ValueError('Each shaft measurement requires both kernels')
    indices = tuple(134+72*flat for flat in range(5))
    free_bands = []
    for index in indices:
        pair = [row for row in bands if row['index'] == index]
        if len(pair) != 2 or {row['kernel'] for row in pair} != {'native', 'faceted'}:
            raise ValueError(f'Indexed flat {index} requires one record per kernel')
        if any(row.get('crank') != 0 for row in pair):
            raise ValueError('Indexed bands must be measured at crank 0')
        for row in pair:
            if len(row['bounds']) != 2 or any(
                    bound['free_mm3'] > 0 or bound['contact_mm3'] <= 0
                    for bound in row['bounds']):
                raise ValueError('A band must retain free and contacting endpoints')
        low = max(row['bounds'][0]['last_free'] for row in pair)
        high = min(row['bounds'][1]['last_free'] for row in pair)
        if not low <= index <= high:
            raise ValueError(f'Indexed flat {index} is outside its measured free band')
        free_bands.append((low, high))
    if len(bands) != 10:
        raise ValueError('Exactly five complete indexed bands are required')
    sectors = []
    for flat, (_, high) in enumerate(free_bands):
        start = high-SHAFT_GUARD
        end = free_bands[(flat+1) % 5][0]+SHAFT_GUARD+(360 if flat == 4 else 0)
        points = []
        for shaft in sorted(by_kernel['native']):
            if not start < shaft < end:
                continue
            openings, closings = [], []
            for kernel in ('native', 'faceted'):
                boundaries = by_kernel[kernel][shaft]['boundaries']
                if len(boundaries) != 2:
                    raise ValueError(f'{shaft}, {kernel}: expected exactly two boundaries')
                opening, closing = boundaries
                if opening['enters_contact'] or not closing['enters_contact']:
                    raise ValueError(f'{shaft}, {kernel}: unexpected contact ordering')
                if not 0 <= opening['left'] <= opening['right'] < closing['left'] <= closing['right'] <= 360:
                    raise ValueError(f'{shaft}, {kernel}: invalid boundary brackets')
                openings.append(opening['right'])
                closings.append(closing['left'])
            points.append((shaft, max(openings), min(closings)))
        if len(points) < 3:
            raise ValueError(f'Flat {flat} lacks three measured contact knots')
        sectors.append((start, end, tuple(points)))
    return tuple(sectors)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--envelopes', type=Path, action='append', required=True)
    parser.add_argument('--bands', type=Path, required=True)
    args = parser.parse_args()
    rows = {}
    for path in args.envelopes:
        for line in path.read_text().splitlines():
            if line.startswith('{'):
                row = json.loads(line)
                if 'kernel' in row:
                    rows[(row['shaft'], row['kernel'])] = row
    bands = json.loads(args.bands.read_text())['rows']
    sectors = compile_profile(list(rows.values()), bands)
    lines = ['"""Provisional measured complete-print counter-ones contact sectors.',
             '', 'Not adopted. Validate boundaries, interpolation and retained motion.',
             'Generated by tools/compile_counter_locking_profile.py.', '"""', '']
    for path in [*args.envelopes, args.bands]:
        lines.append(f'# {path.name}: SHA-256 {hashlib.sha256(path.read_bytes()).hexdigest()}')
    lines.extend(['', 'SECTORS = ('])
    for start, end, points in sectors:
        lines.append(f'    ({start!r}, {end!r}, (')
        lines.extend(f'        {point!r},' for point in points)
        lines.append('    )),')
    lines.append(')')
    target = Path(__file__).resolve().parents[1]/'counter_locking_profiles.py'
    print('*** Begin Patch')
    if target.exists():
        print(f'*** Update File: {target}\n@@')
        print('\n'.join('-'+line for line in target.read_text().splitlines()))
    else:
        print(f'*** Add File: {target}')
    print('\n'.join('+'+line for line in lines))
    print('*** End Patch')


if __name__ == '__main__':
    main()
