"""Source placements reorganized into independently visible teaching layers.

Generated by tools/layer_import.py; geometry stays in standard.parts.
The raw standard.assembly remains the independent STEP placement map.
"""
from machinome.node import AssemblyNode
from .assembly import *
from .parts import *

class InputSelectors(AssemblyNode):
    digit_selector_axle_1 = DigitSelectorAxle1()
    digit_selector_axle_4 = DigitSelectorAxle4()
    digit_selector_axle_7 = DigitSelectorAxle7()
    digit_selector_axle_6 = DigitSelectorAxle6()
    digit_selector_axle_2 = DigitSelectorAxle2()
    digit_selector_axle_8 = DigitSelectorAxle8()
    digit_selector_axle_5 = DigitSelectorAxle5()
    digit_selector_axle_3 = DigitSelectorAxle3()


class InputBearings(AssemblyNode):
    selector_shaft_bearing_1 = SelectorShaftBearing()
    selector_shaft_bearing_2 = SelectorShaftBearing()
    selector_shaft_bearing_3 = SelectorShaftBearing()
    selector_shaft_bearing_4 = SelectorShaftBearing()
    selector_shaft_bearing_5 = SelectorShaftBearing()
    selector_shaft_bearing_6 = SelectorShaftBearing()
    selector_shaft_bearing_7 = SelectorShaftBearing()
    selector_shaft_bearing_8 = SelectorShaftBearing()
    setting_axle_holding_plate_1 = SettingAxleHoldingPlate()
    setting_axle_holding_plate_2 = SettingAxleHoldingPlate()
    m4x10_419010_2 = M4x10_419010()
    m4x10_419010_3 = M4x10_419010()
    m4x10_419010_4 = M4x10_419010()
    m4x10_419010_5 = M4x10_419010()

    def render(self):
        self.selector_shaft_bearing_1.rotate(-155.687762595, (0.0, 0.0, 1.0))
        self.selector_shaft_bearing_1.translate((-10.158418394, -57.611253551, -138.275))
        self.selector_shaft_bearing_2.rotate(103.351337657, (0.0, 0.0, 1.0))
        self.selector_shaft_bearing_2.translate((-29.25, -50.662486121, -138.275))
        self.selector_shaft_bearing_3.rotate(-57.6058828, (0.0, 0.0, 1.0))
        self.selector_shaft_bearing_3.translate((29.25, -50.662486121, -138.275))
        self.selector_shaft_bearing_4.rotate(-20.373054183, (0.0, 0.0, 1.0))
        self.selector_shaft_bearing_4.translate((-44.813599922, -37.603075167, -138.275))
        self.selector_shaft_bearing_5.rotate(144.2101172, (0.0, 0.0, 1.0))
        self.selector_shaft_bearing_5.translate((44.813599922, -37.603075167, -138.275))
        self.selector_shaft_bearing_6.rotate(-177.191062484, (0.0, 0.0, 1.0))
        self.selector_shaft_bearing_6.translate((58.5, 0.0, -138.275))
        self.selector_shaft_bearing_7.rotate(30.0541172, (0.0, 0.0, 1.0))
        self.selector_shaft_bearing_7.translate((54.972018316, -20.008178385, -138.275))
        self.selector_shaft_bearing_8.rotate(58.176118702, (0.0, 0.0, 1.0))
        self.selector_shaft_bearing_8.translate((10.158418394, -57.611253551, -138.275))
        self.setting_axle_holding_plate_1.rotate(60.0, (0.0, 0.0, 1.0))
        self.setting_axle_holding_plate_1.translate((0.003955464, 0.003318723, -141.45))
        self.setting_axle_holding_plate_2.rotate(-20.0, (0.0, 0.0, 1.0))
        self.setting_axle_holding_plate_2.translate((0.003955163, -0.003319081, -141.45))
        self.m4x10_419010_2.rotate(180.0, (0.984807753, -0.173648178, 0.0))
        self.m4x10_419010_2.translate((-36.638893752, -43.664533258, -132.45))
        self.m4x10_419010_3.rotate(180.0, (0.965925826, -0.258819045, 0.0))
        self.m4x10_419010_3.translate((36.638893752, -43.664533258, -132.45))
        self.m4x10_419010_4.rotate(180.0, (0.984807753, -0.173648178, 0.0))
        self.m4x10_419010_4.translate((0.009118459, -57.003318847, -132.45))
        self.m4x10_419010_5.rotate(180.0, (0.965925826, -0.258819045, 0.0))
        self.m4x10_419010_5.translate((56.138893752, -9.88954251, -132.45))


class Transmission(AssemblyNode):
    p_10236_6 = Part10236_6()
    p_10236_5 = Part10236_5()
    p_10236_9 = Part10236_9()
    p_10236_7 = Part10236_7()
    p_10236_8 = Part10236_8()
    p_10236_2 = Part10236_2()
    p_10236_4 = Part10236_4()
    p_10236_11 = Part10236_11()
    p_10238_3 = Part10238_3()
    p_10238_2 = Part10238_2()
    p_10239_1 = Part10239_1()
    p_10237_1 = Part10237_1()
    p_10238_1 = Part10238_1()
    p_10236_10 = Part10236_10()
    p_10236_1 = Part10236_1()
    p_10236_3 = Part10236_3()
    p_10236_12 = Part10236_12()


class ResultCarry(AssemblyNode):
    results_tens_lever_assembly_10 = ResultsTensLeverAssembly10()
    results_tens_lever_assembly_8 = ResultsTensLeverAssembly8()
    results_tens_lever_assembly_5 = ResultsTensLeverAssembly5()
    results_tens_lever_assembly_2 = ResultsTensLeverAssembly2()
    results_tens_lever_assembly_4 = ResultsTensLeverAssembly4()
    results_tens_lever_assembly_6 = ResultsTensLeverAssembly6()
    results_tens_lever_assembly_3 = ResultsTensLeverAssembly3()
    results_tens_lever_assembly_9 = ResultsTensLeverAssembly9()
    results_tens_lever_assembly_7 = ResultsTensLeverAssembly7()
    results_tens_lever_assembly_1 = ResultsTensLeverAssembly1()


class TurnsCarry(AssemblyNode):
    turns_tens_lever_assembly_5 = TurnsTensLeverAssembly5()
    turns_tens_lever_assembly_3 = TurnsTensLeverAssembly3()
    turns_tens_lever_assembly_2 = TurnsTensLeverAssembly2()
    turns_tens_lever_assembly_4 = TurnsTensLeverAssembly4()
    turns_tens_lever_assembly_1 = TurnsTensLeverAssembly1()


class CarryPivots(AssemblyNode):
    m4x16_hex_1 = M4x16Hex()
    m4x16_hex_2 = M4x16Hex()
    m4x16_hex_3 = M4x16Hex()
    m4x16_hex_4 = M4x16Hex()
    m4x16_hex_5 = M4x16Hex()
    m4x16_hex_6 = M4x16Hex()
    m4x16_hex_7 = M4x16Hex()
    m4x16_hex_8 = M4x16Hex()
    m4x16_hex_9 = M4x16Hex()
    m4x16_hex_10 = M4x16Hex()
    m4x16_hex_11 = M4x16Hex()
    m4x16_hex_12 = M4x16Hex()
    m4x16_hex_13 = M4x16Hex()
    m4x16_hex_14 = M4x16Hex()
    m4x16_hex_15 = M4x16Hex()

    def render(self):
        self.m4x16_hex_1.rotate(100.288585137, (0.834817129, 0.389281621, 0.389281621))
        self.m4x16_hex_1.translate((25.787362927, -39.77027397, 4.8))
        self.m4x16_hex_2.rotate(-91.727941072, (0.970287525, -0.17108787, 0.17108787))
        self.m4x16_hex_2.translate((28.552035412, 37.834429455, 4.8))
        self.m4x16_hex_3.rotate(100.288585137, (0.834817129, -0.389281621, -0.389281621))
        self.m4x16_hex_3.translate((-43.644002724, -18.48955934, 4.8))
        self.m4x16_hex_4.rotate(90.435230002, (0.992432509, 0.086826594, 0.086826594))
        self.m4x16_hex_4.translate((-5.809573269, -47.041594752, 4.8))
        self.m4x16_hex_5.rotate(-91.727941072, (0.970287525, 0.17108787, -0.17108787))
        self.m4x16_hex_5.translate((-2.447374406, 47.335749037, 4.8))
        self.m4x16_hex_6.rotate(180.0, (0.707106781, 0.0, 0.707106781))
        self.m4x16_hex_6.translate((45.318105414, -13.89, 4.8))
        self.m4x16_hex_7.rotate(109.207479725, (0.710564775, -0.497542812, -0.497542812))
        self.m4x16_hex_7.translate((-47.335749037, -2.447374406, 4.8))
        self.m4x16_hex_8.rotate(-90.0, (1.0, 0.0, 0.0))
        self.m4x16_hex_8.translate((13.89, 45.318105414, 4.8))
        self.m4x16_hex_9.rotate(-96.717713464, (0.889126491, 0.323615577, -0.323615577))
        self.m4x16_hex_9.translate((-18.48955934, 43.644002724, 4.8))
        self.m4x16_hex_10.rotate(120.0, (0.577350269, -0.577350269, -0.577350269))
        self.m4x16_hex_10.translate((-45.318105414, 13.89, 4.8))
        self.m4x16_hex_11.rotate(90.435230002, (0.992432509, -0.086826594, -0.086826594))
        self.m4x16_hex_11.translate((-21.54838611, -42.217648376, 4.8))
        self.m4x16_hex_12.rotate(93.840965716, (0.935113127, 0.250562807, 0.250562807))
        self.m4x16_hex_12.translate((10.629959849, -46.19163054, 4.8))
        self.m4x16_hex_13.rotate(109.207479725, (0.710564775, 0.497542812, 0.497542812))
        self.m4x16_hex_13.translate((37.834429455, -28.552035412, 4.8))
        self.m4x16_hex_14.rotate(-96.717713464, (0.889126491, -0.323615577, 0.323615577))
        self.m4x16_hex_14.translate((39.77027397, 25.787362927, 4.8))
        self.m4x16_hex_15.rotate(93.840965716, (0.935113127, -0.250562807, -0.250562807))
        self.m4x16_hex_15.translate((-34.688145566, -32.30163054, 4.8))


class LowerDecimalMarkers(AssemblyNode):
    decimal_marker_1 = DecimalMarker1()
    decimal_marker_2 = DecimalMarker2()
    decimal_marker_3 = DecimalMarker3()
    decimal_marker_4 = DecimalMarker4()
    decimal_marker_5 = DecimalMarker5()


class UpperDecimalMarkers(AssemblyNode):
    decimal_marker_6 = DecimalMarker6()
    decimal_marker_7 = DecimalMarker7()
    decimal_marker_8 = DecimalMarker8()
    decimal_marker_9 = DecimalMarker9()
    decimal_marker_10 = DecimalMarker10()


class CrankAssembly(AssemblyNode):
    crank_handle_1 = CrankHandle1()
    crank_handle_pin = CrankHandlePin()

    def render(self):
        self.crank_handle_pin.rotate(90.989717347, (0.982873666, 0.130306093, 0.130306093))
        self.crank_handle_pin.translate((-5.507637771, 20.444630619, 74.85))


class DrumAssembly(AssemblyNode):
    main_axle_step_drum_1 = MainAxleStepDrum1()


class AntiReversal(AssemblyNode):
    anti_reversal_spring = AntiReversalSpring()
    anti_reversal_m5_bolt_sleeve = AntiReversalM5BoltSleeve()
    reverse_rotation_prevention_pawl = ReverseRotationPreventionPawl()
    m5x15_hex_bolt_2 = M5x15HexBolt()

    def render(self):
        self.anti_reversal_spring.rotate(24.099851655, (0.0, 0.0, 1.0))
        self.anti_reversal_spring.translate((-51.702407033, 9.116529328, -143.7))
        self.anti_reversal_m5_bolt_sleeve.rotate(180.0, (0.0, 0.0, 1.0))
        self.anti_reversal_m5_bolt_sleeve.translate((-51.702407033, 9.116529328, -152.55))
        self.reverse_rotation_prevention_pawl.rotate(180.0, (-0.122734172, 0.992439582, 0.0))
        self.reverse_rotation_prevention_pawl.translate((-51.702407033, 9.116529328, -143.7))
        self.m5x15_hex_bolt_2.rotate(-180.0, (0.707106781, 0.707106781, 0.0))
        self.m5x15_hex_bolt_2.translate((-51.702407033, 9.116529328, -133.95))


class LowerBearingPlate(AssemblyNode):
    bearing_plate = BearingPlate()
    bearing_plate_screw = BearingPlateScrew()
    reverse_nose_plate = ReverseNosePlate()

    def render(self):
        self.bearing_plate.rotate(180.0, (1.0, 0.0, 0.0))
        self.bearing_plate.translate((0.0, 0.0, -118.35))
        self.bearing_plate_screw.rotate(180.0, (1.0, 0.0, 0.0))
        self.bearing_plate_screw.translate((-14.4, 0.0, -111.75))
        self.reverse_nose_plate.rotate(180.0, (0.0, 1.0, 0.0))
        self.reverse_nose_plate.translate((-14.4, 0.0, -116.85))


class ZeroPositioning(AssemblyNode):
    m5_nut_1 = M5Nut()
    zero_positioning_disc_roller = ZeroPositioningDiscRoller()
    m5_nut_2 = M5Nut()
    zero_positioning_disc_securing_spring = ZeroPositioningDiscSecuringSpring()
    disc_roller_bolt_sleeve = DiscRollerBoltSleeve()
    zero_positioning_m5_bolt_sleeve = ZeroPositioningM5BoltSleeve()
    zero_positioning_disc = ZeroPositioningDisc()
    m5x15_hex_bolt_1 = M5x15HexBolt()
    zero_positioning_lever = ZeroPositioningLever()
    m5x30_hex_bolt = M5x30HexBolt()
    zero_positioning_disc_pin = ZeroPositioningDiscPin()
    zero_positioning_spring = ZeroPositioningSpring()

    def render(self):
        self.m5_nut_1.rotate(180.0, (1.0, 0.0, 0.0))
        self.m5_nut_1.translate((40.5, 33.6, -128.25))
        self.zero_positioning_disc_roller.translate((40.5, 0.0, -153.1))
        self.m5_nut_2.rotate(-90.0, (0.0, 0.0, 1.0))
        self.m5_nut_2.translate((40.5, 0.0, -160.5))
        self.zero_positioning_disc_securing_spring.rotate(180.0, (0.999999588, 0.000908294, 0.0))
        self.zero_positioning_disc_securing_spring.translate((0.029065386, -15.9999736, -142.2))
        self.disc_roller_bolt_sleeve.rotate(-90.0, (0.0, 0.0, 1.0))
        self.disc_roller_bolt_sleeve.translate((40.5, 0.0, -153.3))
        self.zero_positioning_m5_bolt_sleeve.rotate(-90.0, (0.0, 0.0, 1.0))
        self.zero_positioning_m5_bolt_sleeve.translate((40.5, 33.6, -161.85))
        self.zero_positioning_disc.rotate(-180.0, (0.70774875, -0.706464229, 0.0))
        self.zero_positioning_disc.translate((0.0, 0.0, -138.45))
        self.m5x15_hex_bolt_1.rotate(-90.0, (0.0, 0.0, 1.0))
        self.m5x15_hex_bolt_1.translate((40.5, 0.0, -161.4))
        self.zero_positioning_lever.rotate(-90.0, (0.0, 0.0, 1.0))
        self.zero_positioning_lever.translate((40.5, 33.6, -156.3))
        self.m5x30_hex_bolt.rotate(180.0, (0.0, 1.0, 0.0))
        self.m5x30_hex_bolt.translate((40.5, 33.6, -128.25))
        self.zero_positioning_disc_pin.rotate(-179.92640235, (0.707106635, 0.000642261, 0.707106635))
        self.zero_positioning_disc_pin.translate((-14.99997525, -0.027248799, -165.75))
        self.zero_positioning_spring.rotate(180.0, (-0.656059029, 0.75470958, 0.0))
        self.zero_positioning_spring.translate((40.49999902, 33.599994789, -142.800003302))


class TensBellAssembly(AssemblyNode):
    tens_bell_1 = TensBell1()
    tens_bell_spring = TensBellSpring()
    tens_bell_c_clip = TensBellCClip()
    retaining_ring_for_tens_bell = RetainingRingForTensBell()

    def render(self):
        self.tens_bell_spring.translate((0.0, 0.0, -8.7))
        self.tens_bell_c_clip.translate((0.0, 0.0, 63.6))
        self.retaining_ring_for_tens_bell.translate((0.0, 0.0, 61.8))


class UpperFrame(AssemblyNode):
    m4x10_419159_1 = M4x10_419159()
    frame_support_1 = FrameSupport()
    main_body = MainBody()
    m4_nut_1 = M4Nut()
    m4_nut_2 = M4Nut()
    m4_nut_3 = M4Nut()
    frame_support_2 = FrameSupport()
    m4x10_419159_2 = M4x10_419159()
    frame_support_3 = FrameSupport()

    def render(self):
        self.m4x10_419159_1.rotate(180.0, (1.0, 0.0, 0.0))
        self.m4x10_419159_1.translate((-10.5, 0.0, -2.7))
        self.frame_support_1.translate((-52.84947971, -21.352575825, -142.95))
        self.m4_nut_1.translate((52.84947971, 21.352575825, -15.9))
        self.m4_nut_2.translate((-52.84947971, -21.352575825, -15.9))
        self.m4_nut_3.translate((-38.140444562, 42.359255052, -15.9))
        self.frame_support_2.translate((-38.140444562, 42.359255052, -142.95))
        self.m4x10_419159_2.rotate(180.0, (1.0, 0.0, 0.0))
        self.m4x10_419159_2.translate((10.5, 0.0, -2.7))
        self.frame_support_3.translate((52.84947971, 21.352575825, -142.95))


class CarriagePositioning(AssemblyNode):
    thrust_ring = ThrustRing()
    carriage_spring_sleeve = CarriageSpringSleeve()
    carriage_spring = CarriageSpring()
    spring_sleeve_c_clip = SpringSleeveCClip()
    p_6mm_ball_419094 = Part6mmBall419094()

    def render(self):
        self.thrust_ring.rotate(35.717779468, (0.0, 0.0, 1.0))
        self.thrust_ring.translate((0.0, 0.0, 25.5225))
        self.carriage_spring_sleeve.rotate(180.0, (1.0, 0.0, 0.0))
        self.carriage_spring_sleeve.translate((0.0, 0.0, 57.6))
        self.carriage_spring.rotate(35.717779468, (0.0, 0.0, 1.0))
        self.carriage_spring.translate((0.0, 0.0, 27.0225))
        self.spring_sleeve_c_clip.translate((0.0, 0.0, 57.6))
        self.p_6mm_ball_419094.rotate(-180.0, (0.707106781, 0.0, -0.707106781))
        self.p_6mm_ball_419094.translate((9.627860318, 0.0, 30.0))


class ReversingAssembly(AssemblyNode):
    reversing_lever_1 = ReversingLever1()


class Enclosure(AssemblyNode):
    cover_ring = CoverRing()
    upper_outer_sleeve = UpperOuterSleeve()
    lower_housing_1 = LowerHousing1()
    base_plate = BasePlate()
    m4x10_419010_6 = M4x10_419010()
    m5x30_countersunk_1 = M5x30Countersunk()
    m5x30_countersunk_2 = M5x30Countersunk()
    m3x10_pan_1 = M3x10Pan()
    m3x10_countersink_screw_1 = M3x10CountersinkScrew()
    m3x10_pan_2 = M3x10Pan()
    m3x10_countersink_screw_2 = M3x10CountersinkScrew()
    m3x10_pan_3 = M3x10Pan()
    m3x10_countersink_screw_3 = M3x10CountersinkScrew()

    def render(self):
        self.cover_ring.translate((0.0, 0.0, 22.2))
        self.upper_outer_sleeve.translate((0.0, 0.0, -40.2))
        self.base_plate.rotate(180.0, (-0.173648178, 0.984807753, 0.0))
        self.base_plate.translate((-0.406900356, 0.745841949, -180.75))
        self.m4x10_419010_6.rotate(83.262779635, (-0.33858732, 0.466025466, 0.817422101))
        self.m4x10_419010_6.translate((20.729374904, 65.796608357, -152.594722215))
        self.m5x30_countersunk_1.rotate(-70.0, (0.0, 0.0, 1.0))
        self.m5x30_countersunk_1.translate((19.088247813, -52.816637436, -186.75))
        self.m5x30_countersunk_2.rotate(-70.0, (0.0, 0.0, 1.0))
        self.m5x30_countersunk_2.translate((-19.902048526, 54.308321334, -186.75))
        self.m3x10_pan_1.translate((47.523550653, 12.733897019, 15.0))
        self.m3x10_countersink_screw_1.rotate(165.893955739, (0.701673843, -0.12372403, 0.701673843))
        self.m3x10_countersink_screw_1.translate((55.969284246, -20.371153499, 19.8))
        self.m3x10_pan_2.translate((-16.827391052, -46.232876943, 15.0))
        self.m3x10_countersink_screw_2.rotate(92.900575802, (0.950614905, -0.219466743, -0.219466743))
        self.m3x10_countersink_screw_2.translate((-26.109941461, -53.533313281, 19.8))
        self.m3x10_pan_3.translate((-40.302280579, 28.219960668, 15.0))
        self.m3x10_countersink_screw_3.rotate(-165.893955739, (0.701673843, -0.12372403, -0.701673843))
        self.m3x10_countersink_screw_3.translate((-55.969284246, 20.371153499, 19.8))


class ClearingAssembly(AssemblyNode):
    m4x10_419010_1 = M4x10_419010()
    clearing_ring_rivet_1 = ClearingRingRivet()
    clearing_ring_rivet_2 = ClearingRingRivet()
    clearing_ring = ClearingRing()

    def render(self):
        self.m4x10_419010_1.rotate(47.531056002, (-0.129842301, 0.94068028, 0.313467044))
        self.m4x10_419010_1.translate((43.908248282, 12.219569698, 45.574328291))
        self.clearing_ring_rivet_1.rotate(-74.282220532, (0.0, 0.0, 1.0))
        self.clearing_ring_rivet_1.translate((39.372124643, 10.943003894, 50.5))
        self.clearing_ring_rivet_2.rotate(-74.282220532, (0.0, 0.0, 1.0))
        self.clearing_ring_rivet_2.translate((37.348717788, -16.582726336, 50.5))
        self.clearing_ring.rotate(180.0, (0.603780106, 0.797150916, 0.0))
        self.clearing_ring.translate((50.343540869, -28.04260917, 62.56))


class FrameFasteners(AssemblyNode):
    m4_nut_1 = M4Nut()
    m4_nut_2 = M4Nut()
    m4_nut_3 = M4Nut()
    m4_nut_4 = M4Nut()

    def render(self):
        self.m4_nut_1.translate((-52.84947971, -21.352575825, -142.05))
        self.m4_nut_2.translate((17.613968679, 54.210221429, -15.9))
        self.m4_nut_3.translate((-38.140444562, 42.359255052, -142.05))
        self.m4_nut_4.translate((52.84947971, 21.352575825, -142.05))


class RegisterDetents(AssemblyNode):
    p_6mm_ball_419241_1 = Part6mmBall419241()
    p_6mm_ball_419241_2 = Part6mmBall419241()
    p_6mm_ball_419241_3 = Part6mmBall419241()
    p_6mm_ball_419241_4 = Part6mmBall419241()
    p_6mm_ball_419241_5 = Part6mmBall419241()
    p_6mm_ball_419241_6 = Part6mmBall419241()
    p_6mm_ball_419241_7 = Part6mmBall419241()
    p_6mm_ball_419241_8 = Part6mmBall419241()
    p_6mm_ball_419241_9 = Part6mmBall419241()
    p_6mm_ball_419241_10 = Part6mmBall419241()
    p_6mm_ball_419241_11 = Part6mmBall419241()
    p_6mm_ball_419241_12 = Part6mmBall419241()
    p_6mm_ball_419241_13 = Part6mmBall419241()
    p_6mm_ball_419241_14 = Part6mmBall419241()
    p_6mm_ball_419241_15 = Part6mmBall419241()
    p_6mm_ball_419241_16 = Part6mmBall419241()
    spider_spring = SpiderSpring()
    p_6mm_ball_419241_17 = Part6mmBall419241()

    def render(self):
        self.p_6mm_ball_419241_1.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_1.translate((41.611836805, -14.543025222, 43.35))
        self.p_6mm_ball_419241_2.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_2.translate((-27.78108269, 33.060447395, 43.35))
        self.p_6mm_ball_419241_3.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_3.translate((-6.614320319, -43.007025353, 43.35))
        self.p_6mm_ball_419241_4.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_4.translate((-32.560903643, -28.356981008, 43.35))
        self.p_6mm_ball_419241_5.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_5.translate((-40.536394735, 14.466670656, 43.35))
        self.p_6mm_ball_419241_6.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_6.translate((28.215994571, 33.59791604, 43.35))
        self.p_6mm_ball_419241_7.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_7.translate((-20.879211024, -37.969544529, 43.35))
        self.p_6mm_ball_419241_8.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_8.translate((-43.02027263, -0.456253672, 43.35))
        self.p_6mm_ball_419241_9.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_9.translate((0.119644646, 43.519816382, 43.35))
        self.p_6mm_ball_419241_10.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_10.translate((15.042568974, 41.035938487, 43.35))
        self.p_6mm_ball_419241_11.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_11.translate((8.513212127, -42.861828947, 43.35))
        self.p_6mm_ball_419241_12.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_12.translate((44.0957147, 0.379899106, 43.35))
        self.p_6mm_ball_419241_13.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_13.translate((34.173814358, -27.716450819, 43.35))
        self.p_6mm_ball_419241_14.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_14.translate((-14.752853499, 40.749957394, 43.35))
        self.p_6mm_ball_419241_15.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_15.translate((38.051011892, 22.102884323, 43.35))
        self.p_6mm_ball_419241_16.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_16.translate((22.678782641, -37.551468141, 43.35))
        self.spider_spring.rotate(0.549916905, (0.0, 0.0, 1.0))
        self.spider_spring.translate((0.537721035, -0.038177283, 45.2))
        self.p_6mm_ball_419241_17.rotate(-180.0, (-0.004798912, 0.999988485, 0.0))
        self.p_6mm_ball_419241_17.translate((-40.250413642, -15.328751817, 43.35))


class CarriageStructure(AssemblyNode):
    crank_collar_washer = CrankCollarWasher()
    crank_collar_nut = CrankCollarNut()
    crank_collar = CrankCollar()
    upper_carriage_body_1 = UpperCarriageBody1()

    def render(self):
        self.crank_collar_washer.rotate(180.0, (0.797150916, -0.603780106, 0.0))
        self.crank_collar_washer.translate((0.0, 0.0, 60.3))
        self.crank_collar_nut.rotate(-54.282220532, (0.0, 0.0, 1.0))
        self.crank_collar_nut.translate((0.0, 0.0, 12.3))
        self.crank_collar.rotate(-144.282220532, (0.0, 0.0, 1.0))
        self.crank_collar.translate((0.0, 0.0, 7.8))


class ResultRegister(AssemblyNode):
    p_10204_3 = Part10204_3()
    results_dial_type_2_1 = ResultsDialType2()
    p_10205_1 = Part10205_1()
    p_10204_6 = Part10204_6()
    p_10204_1 = Part10204_1()
    p_10205_2 = Part10205_2()
    p_10204_2 = Part10204_2()
    p_10204_4 = Part10204_4()
    p_10203_1 = Part10203_1()
    p_10204_5 = Part10204_5()
    p_10203_2 = Part10203_2()

    def render(self):
        self.results_dial_type_2_1.rotate(109.481790438, (0.706968432, 0.500097809, 0.500097809))
        self.results_dial_type_2_1.translate((-66.857451389, 23.761646754, 33.9))


class TurnsRegister(AssemblyNode):
    p_10205_4 = Part10205_4()
    results_dial_type_2_2 = ResultsDialType2()
    p_10203_3 = Part10203_3()
    p_10203_4 = Part10203_4()
    p_10204_7 = Part10204_7()
    p_10205_3 = Part10205_3()

    def render(self):
        self.results_dial_type_2_2.rotate(104.232401654, (0.778024743, -0.444228263, -0.444228263))
        self.results_dial_type_2_2.translate((62.090225773, 36.291288041, 33.9))


class CarriageCovers(AssemblyNode):
    digits_cover = DigitsCover()
    upper_housing = UpperHousing()
    clearing_cover = ClearingCover()

    def render(self):
        self.digits_cover.rotate(-180.0, (0.168920173, 0.985629735, 0.0))
        self.digits_cover.translate((0.386511579, -0.028412332, 31.6))
        self.upper_housing.rotate(160.549916905, (0.0, 0.0, 1.0))
        self.upper_housing.translate((0.386511579, -0.028412332, -4.4))
        self.clearing_cover.rotate(180.0, (0.797150916, -0.603780106, 0.0))
        self.clearing_cover.translate((0.386511579, -0.028412332, 57.1))
