"""Measured drum-pocket profile with .05 mm radial seating allowance.

Generated by tools/compile_bell_spring.py; no live collision solving.
"""

from machinome.math import piecewise


DEFLECTION = (
    (0, 6.856519),
    (0.1, 6.902295),
    (0.15, 6.921826),
    (1.35, 7.199353),
    (1.4, 7.209912),
    (1.7, 7.269116),
    (1.75, 7.270886),
    (2.05, 7.259167),
    (2.1, 7.255688),
    (3.3, 7.151196),
    (3.35, 7.143018),
    (3.65, 7.059033),
    (3.7, 7.040662),
    (4.8, 6.574292),
    (4.85, 6.551587),
    (5.05, 6.445447),
    (5.1, 6.417676),
    (5.3, 6.254773),
    (5.35, 6.212537),
    (6.25, 5.430859),
    (6.3, 5.384839),
    (7.5, 4.193616),
    (7.55, 4.161511),
    (9, 4.161511),
)


def positioning(source, target):
    return lambda subtract: piecewise(9 * subtract, DEFLECTION)
